### ISSUE TITLE
Non blocking semaphores / mutex

### ISSUE THREAD

**Issue by antoinealb** [cvra/platform-abstraction#11]
We should perhaps implement a non blocking version of `os_semaphore_take` and `os_mutex_take` which would simply do an atomic test-and-set and return if the operation suceeded or not.

**Comment by froj** [comment]
Yes. And also blocking with timeout.

**Comment by antoinealb** [comment]
+1 for blocking with timeout. Now for the timeout format : `float` in seconds ? `int` in milliseconds ? `int` in microseconds ?

**Comment by froj** [comment]
I like seconds because SI, but milli- or microseconds would probably be more readable.

**Comment by antoinealb** [comment]
I think we can agree that this is low-level enough to allow non-SI units, but **not** weird non-physical units like processor ticks or whatever.

**Comment by froj** [comment]
> **not** weird non-physical units like processor ticks or whatever

+1

**Comment by pierluca** [comment]
+1
(favoring float milliseconds or uint32 microseconds)

**Comment by antoinealb** [comment]
Fixed in PR #17 .
