### ISSUE TITLE
Support for FreeRTOS

### ISSUE THREAD

**Issue by antoinealb** [cvra/platform-abstraction#29]
So, a good solution to the problem of adding uc/os-iii to the repository would be to support FreeRTOS (www.freertos.org) instead. Since we rely on abstractions, the switch would be easy.

What do you guys think ?

**Comment by Stapelzeiger** [comment]
Just to clarify, do you want to switch to FreeRTOS or would this be a fallback if uc/os-iii is not available for the build?

**Comment by antoinealb** [comment]
If we go down the FreeRTOS route, I would only support it. Not much point in maintaining two OS bindings.

**Comment by Stapelzeiger** [comment]
I would prefer to stick with uc/os-ii/iii. It looks cleaner and we have some experience using it.

**Comment by antoinealb** [comment]
Okie, I don't mind. It will probably require us to do a bit of port work since the official port is based on IAR and not GCC.
