### ISSUE TITLE
Semaphore operations naming

### ISSUE THREAD

**Issue by msplr** [cvra/platform-abstraction#37]
Are `take` and `release` really the right names for semaphore operations?
What about something like `pend` or  `wait` instead of `take` and `signal` or `post` instead `release`?
In my eyes it looks strange to use `os_semaphore_release()` to wake a blocking thread, since `release` rather reminds me of a lock and not a signaling method.
What do you think?

**Comment by antoinealb** [comment]
I already got biten by that, so I vote for a naming change. My vote goes to `pend` and `signal`.

**Comment by msplr** [comment]
+1 for `pend` and `signal`

**Comment by pierluca** [comment]
From a linguistic point of view, I'd prefer `wait` to `pend`.
Pend gives the idea of indecision, unlike wait.

**Comment by antoinealb** [comment]
So `pend` is more appropriate as you don't know if the semaphore will be signaled.

**Comment by pierluca** [comment]
Not really.

pend
1. to await judgment or settlement
2. to hang; depend
or
1. to remain undecided or unsettled.

It's not indecision as in "Waiting for Godot" but rather indecision as "who knows what will happen to this".

On the other hand:

wait 
a. To remain or rest in expectation
b. To tarry until another catches up.

**Comment by 31415us** [comment]
since semaphores are just somewhat glorified counters what about inc and dec?

**Comment by antoinealb** [comment]
P & V #troll
