### ISSUE TITLE
timestamps

### ISSUE THREAD

**Issue by 31415us** [cvra/platform-abstraction#42]
at some point we're going to need timestamps to measure time and timedifferences. we should discuss resolutions (milli-, micro-, nano-) and how to achieve synchronization.

**Comment by antoinealb** [comment]
Yeah, its time to do it. http://stream1.gifsoup.com/view1/1336353/horatio-lunettes-o.gif

**Comment by antoinealb** [comment]
More seriously : unsigned int, 32 bits, microseconds ?

**Comment by msplr** [comment]
+1 for uint32 in us

**Comment by msplr** [comment]
``` C
/** Get a timestamp in microseconds */
uint32_t os_timestamp(void);

/** Updates the timestamp and returns the difference to the previous. */
uint32_t os_timestamp_update(uint32_t *ts);
```

Something like that?

**Comment by 31415us** [comment]
hmm what happens if you update with a past value? or more precisely what exactly are the responsibilities of os_timestamp_update?

**Comment by msplr** [comment]
``` C
uint32_t os_timestamp_update(uint32_t *ts)
{
    uint32_t diff, now;
    now = os_timestamp();
    diff = now - *ts;
    *ts = now;
    return diff;
}
```

I thought this would be a regular use case, so we could implement it in a simple function directly.

**Comment by antoinealb** [comment]
I think actually expanding the computation in caller code is more readable.

**Comment by antoinealb** [comment]
By the way after a bit of thinking I would split this functionality into two modules : The local timestamp in platform abstraction and the clock sync in the network / bus module. What do you think ?

**Comment by 31415us** [comment]
@antoinealb yeah i agree that it's best to separate those two

**Comment by Stapelzeiger** [comment]
We neet two sorts of timestamps anyway. One monotonic for computation and one that is synced.
For the monotonic we should have a function like the one nuft proposed, because it will be used a lot. We could find a clearer name for it though.

**Comment by antoinealb** [comment]
Maybe something more explicit like `timestamp_diff_and_update`.

**Comment by Stapelzeiger** [comment]
yes, that looks good

**Comment by msplr** [comment]
sounds good.

**Comment by msplr** [comment]
I think `timestamp_diff_and_update()` should also be atomic.

**Comment by Stapelzeiger** [comment]
It should be enough if the timestamp function is atomic

**Comment by antoinealb** [comment]
The timestamp function obviously has to be atomic, doesn't it ?

**Comment by Stapelzeiger** [comment]
Well, yes.
